# Book settings
title: The Social Science Network
author: Frederik Kilpinen, Emilie Munch Gregersen, Matias Piqueras
logo: 'logo.png'

latex:
  latex_documents:
    targetname: book.tex

bibtex_bibfiles:
    - references.bib

sphinx:
  config:
    bibtex_reference_style: author_year
    html_extra_path: ['plots']
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
    nb_render_priority:
     html:
      - "application/vnd.jupyter.widget-view+json"
      - "application/javascript"
      - "text/html"
      - "image/svg+xml"
      - "image/png"
      - "image/jpeg"
      - "text/markdown"
      - "text/latex"
      - "text/plain"

# Information about where the book exists on the web
repository:
  url: https://github.com/MatPiq/DTU-social-graphs-project-book # Online location of your book
  branch: master  # Which branch of the repository should be used when creating links (optional)

launch_buttons:
  notebook_interface: "jupyterlab"
  binderhub_url: "https://mybinder.org/v2/gh/MatPiq/DTU-social-graphs-project-book/HEAD" # The URL for your BinderHub (e.g., https://mybinder.org)
  thebe: true
  colab_url: "https://colab.research.google.com"