# Book settings
title: The Social Science Network
author: Frederik Kilpinen, Emilie Munch Gregersen, Matias Piqueras
logo: 'logo.png'

latex:
  latex_documents:
    targetname: book.tex

bibtex_bibfiles:
    - references.bib

sphinx:
  config:
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js